import { NextResponse } from 'next/server';

export interface StartupData {
  id: string;
  name: string;
  sector: string;
  region: 'India' | 'US' | 'Europe' | 'Global';
  valuation: number; // in $B
  lastRound: string; // e.g. "Series G"
  lastRoundAmount: number; // in $M
  leadVCs: string[];
  founded: number; // year
  ipoOutlook: 'Soon' | '2026' | '2027' | '2028+' | 'Unknown' | 'Listed';
  ipoNotes: string;
  description: string;
  tags: string[];
  predictionEventId?: string; // links to prediction market event
}

const STARTUPS: StartupData[] = [
  // ── Global AI Unicorns ────────────────────────────────
  {
    id: 'openai',
    name: 'OpenAI',
    sector: 'Artificial Intelligence',
    region: 'US',
    valuation: 157,
    lastRound: 'Series G',
    lastRoundAmount: 6600,
    leadVCs: ['Thrive Capital', 'Microsoft', 'SoftBank'],
    founded: 2015,
    ipoOutlook: '2027',
    ipoNotes: 'Targeting IPO after 2026 restructuring to for-profit entity',
    description: 'Creator of ChatGPT, GPT-4o and DALL·E. The most widely deployed AI platform globally with 200M+ weekly active users.',
    tags: ['LLM', 'ChatGPT', 'AGI', 'API'],
    predictionEventId: 'startup-0',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    sector: 'Artificial Intelligence',
    region: 'US',
    valuation: 61,
    lastRound: 'Series E',
    lastRoundAmount: 7300,
    leadVCs: ['Amazon', 'Google', 'Spark Capital'],
    founded: 2021,
    ipoOutlook: 'Unknown',
    ipoNotes: 'No IPO plans announced; long-term AI safety focus',
    description: 'Built by ex-OpenAI researchers. Claude models compete directly with GPT-4 on coding, reasoning and safety benchmarks.',
    tags: ['Claude', 'Safety', 'LLM', 'AWS'],
    predictionEventId: 'startup-1',
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    sector: 'Artificial Intelligence',
    region: 'US',
    valuation: 50,
    lastRound: 'Series B',
    lastRoundAmount: 6000,
    leadVCs: ['Andreessen Horowitz', 'Sequoia', 'Elon Musk'],
    founded: 2023,
    ipoOutlook: '2027',
    ipoNotes: 'Musk hinted at potential IPO post-Twitter/X restructuring',
    description: "Elon Musk's AI company powering Grok, deeply integrated with X (Twitter). Has access to real-time X data — a unique competitive advantage.",
    tags: ['Grok', 'X', 'Real-time AI'],
    predictionEventId: 'startup-2',
  },
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    sector: 'AI Search',
    region: 'US',
    valuation: 9,
    lastRound: 'Series C',
    lastRoundAmount: 500,
    leadVCs: ['IVP', 'Nvidia', 'NEA', 'Jeff Bezos'],
    founded: 2022,
    ipoOutlook: '2027',
    ipoNotes: 'Fast growth; IPO likely after hitting $1B ARR milestone',
    description: 'AI-powered search engine that cites sources. Growing fastest in developer and research communities. Direct threat to Google Search.',
    tags: ['Search', 'RAG', 'Citations', 'Nvidia'],
    predictionEventId: 'startup-3',
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    sector: 'Artificial Intelligence',
    region: 'Europe',
    valuation: 6,
    lastRound: 'Series B',
    lastRoundAmount: 1000,
    leadVCs: ['General Catalyst', 'Andreessen Horowitz', 'BNP Paribas'],
    founded: 2023,
    ipoOutlook: '2028+',
    ipoNotes: 'EU-based; potential acquisition target by major tech firm',
    description: "Europe's most prominent AI startup. Open-source and proprietary models competitive with OpenAI. Strong enterprise traction across EU.",
    tags: ['Open Source', 'EU AI', 'Enterprise', 'LLM'],
    predictionEventId: 'startup-4',
  },
  {
    id: 'figure-ai',
    name: 'Figure AI',
    sector: 'Robotics',
    region: 'US',
    valuation: 39,
    lastRound: 'Series B',
    lastRoundAmount: 2600,
    leadVCs: ['Microsoft', 'OpenAI', 'Nvidia', 'Jeff Bezos'],
    founded: 2022,
    ipoOutlook: '2028+',
    ipoNotes: 'Pre-revenue; commercialization expected 2026-2027',
    description: 'Building humanoid robots for commercial use. Partnered with BMW for factory deployment. Figure 02 walks, reasons and handles objects autonomously.',
    tags: ['Humanoid', 'Manufacturing', 'BMW', 'OpenAI'],
    predictionEventId: 'startup-5',
  },
  {
    id: 'waymo',
    name: 'Waymo',
    sector: 'Autonomous Vehicles',
    region: 'US',
    valuation: 45,
    lastRound: 'Series C',
    lastRoundAmount: 5600,
    leadVCs: ['Alphabet', 'Silver Lake', 'Tiger Global'],
    founded: 2009,
    ipoOutlook: '2027',
    ipoNotes: 'Alphabet considering spin-off as standalone public company',
    description: 'Google\'s autonomous driving division. Operates robotaxi service in Phoenix, SF, and Los Angeles with 50,000+ paid rides per week.',
    tags: ['Robotaxi', 'Alphabet', 'Autonomous', 'Google'],
    predictionEventId: 'startup-6',
  },
  {
    id: 'runway',
    name: 'Runway ML',
    sector: 'Generative AI / Video',
    region: 'US',
    valuation: 4,
    lastRound: 'Series D',
    lastRoundAmount: 308,
    leadVCs: ['Google', 'Salesforce Ventures', 'Felicis'],
    founded: 2018,
    ipoOutlook: '2028+',
    ipoNotes: 'Growing fast; IPO dependent on Gen2/Gen3 video model adoption',
    description: 'Leading AI video generation platform (Gen-2, Gen-3). Used by Hollywood studios and major advertising agencies for AI-generated content.',
    tags: ['Video Generation', 'Hollywood', 'Creative AI'],
    predictionEventId: 'startup-8',
  },
  // ── Global FinTech / B2B ───────────────────────────────
  {
    id: 'stripe',
    name: 'Stripe',
    sector: 'Payments / FinTech',
    region: 'US',
    valuation: 65,
    lastRound: 'Series I',
    lastRoundAmount: 6500,
    leadVCs: ['Sequoia', 'Andreessen Horowitz', 'Founders Fund', 'Tiger Global'],
    founded: 2010,
    ipoOutlook: '2026',
    ipoNotes: 'S-1 filing widely expected in 2026; processing $1T+ annually',
    description: 'The payments infrastructure backbone of the internet. Powers Shopify, Amazon, and millions of startups. Annual payment volume exceeds $1 trillion.',
    tags: ['Payments', 'APIs', 'Enterprise', 'IPO Watch'],
    predictionEventId: 'startup-9',
  },
  {
    id: 'klarna',
    name: 'Klarna',
    sector: 'Buy Now Pay Later / FinTech',
    region: 'Europe',
    valuation: 14.6,
    lastRound: 'Pre-IPO',
    lastRoundAmount: 800,
    leadVCs: ['Sequoia', 'SoftBank', 'Silver Lake'],
    founded: 2005,
    ipoOutlook: '2026',
    ipoNotes: 'NYSE IPO S-1 filed; listing expected Q3/Q4 2026',
    description: 'European BNPL giant with 150M+ active consumers. Returned to profitability in 2024. AI-first strategy reshaping consumer credit.',
    tags: ['BNPL', 'Consumer Credit', 'EU FinTech', 'IPO Ready'],
    predictionEventId: 'startup-10',
  },
  {
    id: 'databricks',
    name: 'Databricks',
    sector: 'Data / AI Infrastructure',
    region: 'US',
    valuation: 62,
    lastRound: 'Series J',
    lastRoundAmount: 10000,
    leadVCs: ['Andreessen Horowitz', 'Google Ventures', 'Microsoft', 'NVIDIA'],
    founded: 2013,
    ipoOutlook: '2027',
    ipoNotes: 'Largest private AI infra company; IPO anticipated post-2026 ARR milestone',
    description: 'Data and AI lakehouse platform. $2.4B ARR, growing 60% YoY. Powers data pipelines for 60% of Fortune 500 companies.',
    tags: ['Data Lakehouse', 'Spark', 'LLM Ops', 'Enterprise'],
    predictionEventId: 'startup-11',
  },
  {
    id: 'canva',
    name: 'Canva',
    sector: 'Design / SaaS',
    region: 'Global',
    valuation: 49,
    lastRound: 'Series F',
    lastRoundAmount: 200,
    leadVCs: ['Franklin Templeton', 'T. Rowe Price', 'Sequoia'],
    founded: 2013,
    ipoOutlook: '2026',
    ipoNotes: 'Profitable; NYSE IPO discussions underway',
    description: 'Visual design platform with 170M+ users. AI-powered magic tools. Profitable and growing into enterprise. The \"Microsoft Office\" of design.',
    tags: ['Design', 'SaaS', 'Creative Tools', 'B2C + B2B'],
    predictionEventId: 'startup-12',
  },
  {
    id: 'spacex',
    name: 'SpaceX',
    sector: 'Aerospace / Satellite',
    region: 'US',
    valuation: 350,
    lastRound: 'Secondary',
    lastRoundAmount: 1500,
    leadVCs: ['Andreessen Horowitz', 'Founders Fund', 'Google'],
    founded: 2002,
    ipoOutlook: 'Unknown',
    ipoNotes: 'Musk says no IPO until Starlink is generating reliable cash flow',
    description: "World's most valuable private company. Starlink serves 4M+ subscribers globally. Starship is the most powerful rocket ever built. Reusable first-stage is standard.",
    tags: ['Rockets', 'Starlink', 'Starship', 'Satellite Internet'],
    predictionEventId: 'startup-14',
  },
  // ── Indian Unicorns ────────────────────────────────────
  {
    id: 'zepto',
    name: 'Zepto',
    sector: 'Quick Commerce',
    region: 'India',
    valuation: 5,
    lastRound: 'Series G',
    lastRoundAmount: 665,
    leadVCs: ['StepStone Group', 'Nexus Venture Partners', 'Y Combinator'],
    founded: 2021,
    ipoOutlook: '2027',
    ipoNotes: 'IPO target set for 2027; aiming for ₹40,000 Cr+ valuation',
    description: '10-minute grocery delivery. India\'s fastest-growing quick commerce startup. Expanding dark store network to Tier 2 cities. Direct competitor to Swiggy Instamart and Blinkit.',
    tags: ['Quick Commerce', 'Grocery', 'India', 'D2C'],
    predictionEventId: 'startup-15',
  },
  {
    id: 'phonepe',
    name: 'PhonePe',
    sector: 'Digital Payments',
    region: 'India',
    valuation: 12,
    lastRound: 'Series A (Post-Spin)',
    lastRoundAmount: 1000,
    leadVCs: ['Walmart', 'General Atlantic', 'Tiger Global'],
    founded: 2015,
    ipoOutlook: '2027',
    ipoNotes: 'Targeting India IPO in 2027; HQ moved from Singapore to India',
    description: "India's #1 UPI payments app with 500M+ registered users. Expanding into insurance, mutual funds, and lending via PhonePe Indus Appstore.",
    tags: ['UPI', 'Digital Payments', 'India FinTech', 'Walmart'],
    predictionEventId: 'startup-16',
  },
  {
    id: 'razorpay',
    name: 'Razorpay',
    sector: 'Payments / FinTech',
    region: 'India',
    valuation: 7.5,
    lastRound: 'Series F',
    lastRoundAmount: 375,
    leadVCs: ['GIC Singapore', 'Lone Pine Capital', 'Y Combinator'],
    founded: 2014,
    ipoOutlook: '2027',
    ipoNotes: 'CEO publicly stated IPO readiness by 2027',
    description: "India's leading B2B payments infrastructure. Processing ₹10L+ Crore annually. Expanding internationally to SEA markets with Curlec acquisition.",
    tags: ['Payments', 'B2B', 'India FinTech', 'APIs'],
    predictionEventId: 'startup-17',
  },
  {
    id: 'groww',
    name: 'Groww',
    sector: 'WealthTech / Investing',
    region: 'India',
    valuation: 3,
    lastRound: 'Series F',
    lastRoundAmount: 251,
    leadVCs: ['Sequoia India', 'Tiger Global', 'Y Combinator'],
    founded: 2016,
    ipoOutlook: '2027',
    ipoNotes: 'SEBI registered broker. IPO expected mid-2027',
    description: "India's most popular stock trading and mutual fund app with 40M+ registered investors. #1 broker by active clients on NSE. Now includes credit cards.",
    tags: ['Stocks', 'Mutual Funds', 'India WealthTech', 'Retail Investing'],
    predictionEventId: 'startup-18',
  },
  {
    id: 'swiggy-instamart',
    name: 'Swiggy Instamart',
    sector: 'Quick Commerce',
    region: 'India',
    valuation: 15.1,
    lastRound: 'Listed',
    lastRoundAmount: 11327,
    leadVCs: ['SoftBank', 'Prosus', 'Accel', 'Invesco'],
    founded: 2020,
    ipoOutlook: 'Listed',
    ipoNotes: 'Swiggy IPO completed November 2024 (NSE: SWIGGY)',
    description: 'Swiggy\'s quick commerce arm delivering groceries in 10-30 mins. Head-to-head battle with Zepto and Blinkit in 20+ Indian cities.',
    tags: ['Quick Commerce', 'India', 'Food Delivery', 'NSE Listed'],
    predictionEventId: 'startup-19',
  },
  {
    id: 'meesho',
    name: 'Meesho',
    sector: 'Social Commerce / E-commerce',
    region: 'India',
    valuation: 3.9,
    lastRound: 'Series F',
    lastRoundAmount: 275,
    leadVCs: ['Softbank', 'Sequoia India', 'Meta', 'B Capital'],
    founded: 2015,
    ipoOutlook: '2026',
    ipoNotes: 'Achieved profitability in 2024; IPO in 2026 widely expected',
    description: 'Reseller-powered social commerce platform connecting 150M+ shoppers with Tier 2 and Tier 3 India. Now one of India\'s top 3 e-commerce apps by orders.',
    tags: ['Social Commerce', 'Tier 2/3 India', 'Resellers', 'Profitable'],
    predictionEventId: 'startup-20',
  },
  {
    id: 'ola-electric',
    name: 'Ola Electric',
    sector: 'Electric Vehicles',
    region: 'India',
    valuation: 3.8,
    lastRound: 'Listed',
    lastRoundAmount: 6146,
    leadVCs: ['SoftBank', 'Tiger Global'],
    founded: 2017,
    ipoOutlook: 'Listed',
    ipoNotes: 'Listed on NSE/BSE August 2024. IPO at ₹76 (NSE: OLAELEC)',
    description: "India's #1 EV two-wheeler maker with Futurefactory producing 1M+ scooters. Expanding into motorcycles and 4-wheelers. Ambitious EV battery Gigafactory.",
    tags: ['EV', 'Scooters', 'India Manufacturing', 'NSE Listed'],
    predictionEventId: 'startup-22',
  },
  {
    id: 'zerodha',
    name: 'Zerodha',
    sector: 'Discount Brokerage',
    region: 'India',
    valuation: 3.6,
    lastRound: 'Bootstrapped',
    lastRoundAmount: 0,
    leadVCs: ['None (Bootstrapped)'],
    founded: 2010,
    ipoOutlook: '2028+',
    ipoNotes: 'Founder Nithin Kamath skeptical of IPO; company is profitable and debt-free',
    description: "India's pioneer discount broker and most profitable fintech. 1.3 Cr+ active clients. Built Kite, Coin (mutual funds), and Sensibull (options). Fully bootstrapped.",
    tags: ['Discount Broker', 'Bootstrapped', 'Profitable', 'Kite'],
    predictionEventId: 'startup-23',
  },
  {
    id: 'cred',
    name: 'CRED',
    sector: 'FinTech / Credit',
    region: 'India',
    valuation: 6.4,
    lastRound: 'Series F',
    lastRoundAmount: 140,
    leadVCs: ['GIC Singapore', 'Coatue', 'Sequoia India', 'Tiger Global'],
    founded: 2018,
    ipoOutlook: '2027',
    ipoNotes: 'Kunal Shah targeting profitability by 2025 ahead of IPO',
    description: "India's credit card rewards super-app. 15M+ premium members (750+ credit score). Expanding into travel, commerce, CRED Pay, and peer-to-peer lending.",
    tags: ['Credit Cards', 'Rewards', 'Premium Users', 'India FinTech'],
    predictionEventId: 'startup-24',
  },
  {
    id: 'bharatpe',
    name: 'BharatPe',
    sector: 'Merchant Payments',
    region: 'India',
    valuation: 2.85,
    lastRound: 'Series E',
    lastRoundAmount: 370,
    leadVCs: ['Tiger Global', 'Ribbit Capital', 'Sequoia India'],
    founded: 2018,
    ipoOutlook: '2027',
    ipoNotes: 'Post-governance cleanup; IPO readiness by 2027',
    description: 'UPI QR code and merchant lending platform serving 12M+ merchants. Expanded into Unity Small Finance Bank. Rebuilding post-founder exit with new leadership.',
    tags: ['UPI QR', 'Merchant Lending', 'SMB Finance', 'India'],
    predictionEventId: 'startup-29',
  },
];

export async function GET() {
  return NextResponse.json({
    startups: STARTUPS,
    total: STARTUPS.length,
    lastUpdated: '2026-09-01',
  });
}
