# S&P 500 — all 503 components
SP500_TICKERS = [
    "AAPL","MSFT","NVDA","GOOGL","GOOG","AMZN","META","TSLA","BRK-B","BRK-A",
    "UNH","LLY","JPM","V","XOM","MA","AVGO","PG","HD","COST","MRK","CVX","ABBV",
    "CRM","ACN","MCD","WMT","BAC","NFLX","AMD","PEP","KO","TMO","CSCO","LIN",
    "DHR","ABT","TXN","PM","CMCSA","ORCL","WFC","NEE","RTX","T","BMY","QCOM",
    "INTU","AMGN","UNP","MS","GE","IBM","HON","GS","CAT","SPGI","ISRG","LOW",
    "ELV","BKNG","VRTX","DE","MDLZ","ADI","GILD","BLK","AXP","SYK","REGN","MMC",
    "PLD","SBUX","PANW","CB","CI","ETN","ZTS","BSX","LRCX","KLAC","SO","DUK",
    "NOC","HUM","AON","MO","ITW","TGT","SHW","GD","MCO","CME","EQIX","ICE",
    "EMR","FCX","PH","NSC","CL","FDX","TDG","USB","ROP","APD","CTAS","MSI",
    "ECL","ADSK","ANET","OXY","PCAR","ORLY","AZO","NXPI","MCHP","WDAY","IDXX",
    "MET","PSA","AFL","STZ","EW","SLB","ALL","PGR","TT","A","NKE","CHTR",
    "WELL","MAR","GWW","HLT","CARR","FTNT","AIG","DHI","NEM","PAYX","ODFL",
    "FAST","KMB","CTVA","EFX","MTD","VRSK","MNST","HES","F","GM","LHX","HIG",
    "TEL","SRE","KEYS","OTIS","ROK","AME","BDX","WM","APH","GEHC","FANG",
    "CPRT","GPN","AWK","KHC","CBRE","PCG","EXC","XEL","ED","D","FE","ETR",
    "ACGL","BALL","DTE","CMS","PPL","LNT","AEE","WEC","ES","CNP","NI","PNW",
    "IEX","DOV","CINF","TFC","RF","CFG","FITB","HBAN","NTRS","STT","MTB",
    "KEY","ZION","CMA","SNA","PNR","IR","EXPD","JBHT","UAL","DAL","LUV","AAL",
    "CCL","RCL","NCLH","MGM","LVS","WYNN","CZR","MHK","PHM","LEN","NVR","TOL",
    "BXP","VNO","SLG","CPT","EQR","AVB","UDR","MAA","NNN","O","STOR","WPC",
    "MPW","HR","OHI","PEAK","VTR","SBAC","AMT","CCI","DLR","EQIX","QTS",
    "ARE","BRX","KIM","REG","FRT","SPG","MAC","CBL","TCO","WRI","DDR","AKR",
    "ADC","EPRT","NTST","RCPI","VICI","GLPI","GLP","STAG","TRNO","EXR","LSI",
    "CUZ","PDM","DEI","HPP","CLI","PGRE","ESRT","VRE","NXRT","IIPR","COLD",
    "REXR","CUBE","NSA","JBGS","KRC","BDN","OFC","PKST","FSP","RLJ","RHP",
    "HST","DRH","PEB","SHO","CLDT","APLE","BRAEMAR","INN","CHSP","SVC",
    "NWFL","VHI","ALX","ESBA","JRJR","GOOD","LAND","PSTL","SACH","GPMT",
    "NOW","SNOW","PLTR","NET","DDOG","CRWD","ZS","OKTA","MDB","CFLT","GTLB",
    "UiPath","PATH","AI","C3AI","BBAI","SOUN","RBRK","RDDT","HOOD","COIN",
    "SQ","PYPL","AFRM","UPST","LC","SOFI","NU","DFS","COF","ADS","SYF",
    "ALLY","SC","CACC","ECPG","OMF","WRLD","QRVO","SWKS","XLNX","MRVL",
    "ON","MPWR","ALGM","SITM","WOLF","SLAB","SMTC","CRUS","MTSI","ENPH",
    "FSLR","SEDG","NOVA","ARRY","RUN","SPWR","CSIQ","JKS","DQ","MAXN","SHLS"
]

# Crypto — yfinance format (200 pairs)
CRYPTO_TICKERS = [
    "BTC-USD","ETH-USD","BNB-USD","XRP-USD","SOL-USD","ADA-USD","DOGE-USD",
    "TRX-USD","DOT-USD","MATIC-USD","LTC-USD","SHIB-USD","AVAX-USD","LINK-USD",
    "ATOM-USD","XLM-USD","BCH-USD","XMR-USD","ETC-USD","ALGO-USD","VET-USD",
    "FIL-USD","ICP-USD","APT-USD","ARB-USD","OP-USD","NEAR-USD","HBAR-USD",
    "QNT-USD","GRT-USD","AAVE-USD","MKR-USD","SNX-USD","CRV-USD","UNI-USD",
    "SUSHI-USD","COMP-USD","YFI-USD","1INCH-USD","BAL-USD","ZRX-USD","KNC-USD",
    "MANA-USD","SAND-USD","AXS-USD","GALA-USD","ENJ-USD","CHZ-USD","FLOW-USD",
    "IMX-USD","RNDR-USD","LRC-USD","SKL-USD","CELR-USD","COTI-USD","CTSI-USD",
    "OCEAN-USD","FET-USD","AGIX-USD","NMR-USD","GNO-USD","REP-USD","MLN-USD",
    "REN-USD","BNT-USD","ANKR-USD","CVC-USD","DNT-USD","FUN-USD","MANA-USD",
    "OMG-USD","PAX-USD","POWR-USD","RLC-USD","STORJ-USD","ZEN-USD","ZEC-USD",
    "DASH-USD","DCR-USD","WAVES-USD","QTUM-USD","ONT-USD","ZIL-USD","ICX-USD",
    "IOST-USD","WAN-USD","LSK-USD","NANO-USD","SC-USD","STEEM-USD","DGB-USD",
    "SYS-USD","VIA-USD","XVG-USD","MAID-USD","GAME-USD","XEM-USD","STRAT-USD",
    "KMD-USD","ARDR-USD","NXT-USD","BURST-USD","PPC-USD","NVC-USD","FTC-USD",
    "BTG-USD","ZCL-USD","XZC-USD","PIVX-USD","BLOCK-USD","CLAM-USD","VTC-USD",
    "BLK-USD","UBQ-USD","MONA-USD","RDD-USD","DOGE-USD","VRC-USD","NOTE-USD",
    "MEC-USD","KORE-USD","MINT-USD","AEON-USD","CGB-USD","TRC-USD","SLR-USD",
    "CAP-USD","MAX-USD","NMC-USD","IXC-USD","FLO-USD","XPM-USD","EAC-USD",
    "MZC-USD","NET-USD","TAG-USD","MRC-USD","HBN-USD","APEX-USD","APC-USD",
    "NLG-USD","BTA-USD","GLC-USD","PXI-USD","SXC-USD","ZEIT-USD","BELA-USD",
    "XBC-USD","BIC-USD","DTC-USD","ELP-USD","SUPER-USD","CON-USD","KARMA-USD",
    "CLUB-USD","XCASH-USD","PND-USD","CLOAK-USD","PKB-USD","NYAN-USD","2GIVE-USD",
    "GRS-USD","AUR-USD","AC-USD","IOC-USD","MED-USD","MNE-USD","PROC-USD",
    "CACH-USD","PTC-USD","OSC-USD","KTK-USD","GPS-USD","HODL-USD","XSPEC-USD",
    "SMC-USD","BLC-USD","SOON-USD","XMCC-USD","PHR-USD","XCO-USD","SHND-USD",
    "ARG-USD","MRS-USD","XCN-USD","TOR-USD","BOST-USD","DANK-USD","USNBT-USD",
    "FRN-USD","EDRC-USD","SRC-USD","FLT-USD","EMC2-USD","CANN-USD","GXC-USD",
    "CHIP-USD","SPRTS-USD","XPY-USD","BTB-USD","ADZ-USD","BENJI-USD","TOPAZ-USD"
]

# ETFs (100)
ETF_TICKERS = [
    "SPY","QQQ","VTI","VOO","IWM","DIA","VEA","VWO","EFA","EEM",
    "IEMG","SCHB","ITOT","SPDW","VT","VXUS","GLD","SLV","IAU","GLDM",
    "XLK","XLF","XLE","XLV","XLI","XLB","XLU","XLP","XLRE","XLC",
    "ARKK","ARKG","ARKW","ARKF","ARKQ","IBB","VGT","SOXX","HACK","BOTZ",
    "FINX","BLOK","LIT","ICLN","ACES","TAN","FAN","GRID","PBW","QCLN",
    "TLT","IEF","HYG","LQD","BND","SHY","VGIT","VCIT","VCLT","AGG",
    "MUB","TIP","STIP","VTIP","BNDX","USHY","ANGL","EMHY","FALN","SPSB",
    "VNQ","SCHH","REZ","VNQI","REM","MORT","SRET","KBWY","FFR","HOMZ",
    "GDX","GDXJ","SIL","SILJ","PPLT","PALL","CPER","WOOD","MOO","WEAT",
    "CORN","SOYB","JJG","NIB","CANE","JO","BAL","UNG","USO","BNO"
]

# REITs (50) — individual companies not ETFs
REIT_TICKERS = [
    "AMT","PLD","EQIX","SPG","PSA","DLR","CCI","O","WELL","AVB",
    "EQR","VTR","BXP","ARE","MAA","UDR","NNN","CPT","EXR","SBAC",
    "KIM","REG","FRT","VICI","GLPI","STAG","TRNO","COLD","REXR","CUBE",
    "NSA","IRM","QTS","SLG","VNO","HPP","DEI","KRC","OFC","CLI",
    "RHP","HST","DRH","PEB","APLE","MPW","OHI","PEAK","HR","JBGS"
]

# Commodities (via ETF/futures proxies on yfinance)
COMMODITY_TICKERS = [
    "GC=F","SI=F","CL=F","BZ=F","NG=F","HG=F","PL=F","PA=F",
    "ZW=F","ZC=F","ZS=F","KC=F","CT=F","CC=F","SB=F","OJ=F",
    "LE=F","GF=F","HE=F","LBS=F","RB=F","HO=F","BO=F","ZO=F",
    "ZR=F","ZM=F","GDK=F","DC=F","ZL=F","ZT=F"
]

# Bonds (via ETF proxies on yfinance)
BOND_TICKERS = [
    "TLT","IEF","SHY","BND","AGG","LQD","HYG","JNK",
    "TIP","VTIP","BNDX","EMB","MUB","SHV","GOVT",
    "VGSH","VGIT","VGLT","BSV","BIV","BLV","VCSH","VCIT","VCLT",
    "SCHZ","SCHR","SCHI","SCHQ","STIP","LTPZ"
]

# Indian Stocks (NSE via yfinance .NS suffix)
INDIAN_TICKERS = [
    "RELIANCE.NS","TCS.NS","HDFCBANK.NS","INFY.NS","ICICIBANK.NS",
    "HINDUNILVR.NS","SBIN.NS","BHARTIARTL.NS","ITC.NS","KOTAKBANK.NS",
    "LT.NS","AXISBANK.NS","ASIANPAINT.NS","MARUTI.NS","SUNPHARMA.NS",
    "TITAN.NS","ULTRACEMCO.NS","WIPRO.NS","HCLTECH.NS","BAJFINANCE.NS",
    "NESTLEIND.NS","POWERGRID.NS","NTPC.NS","ONGC.NS","JSWSTEEL.NS",
    "TATAMOTORS.NS","TECHM.NS","ADANIENT.NS","ADANIPORTS.NS","COALINDIA.NS",
    "BAJAJFINSV.NS","HDFCLIFE.NS","SBILIFE.NS","DIVISLAB.NS","DRREDDY.NS",
    "CIPLA.NS","APOLLOHOSP.NS","BRITANNIA.NS","DABUR.NS","MARICO.NS",
    "PIDILITIND.NS","BERGEPAINT.NS","HAVELLS.NS","VOLTAS.NS","WHIRLPOOL.NS",
    "TATACONSUM.NS","UBL.NS","MCDOWELL-N.NS","RADICO.NS","TATACOMM.NS",
    "INDIAMART.NS","NAUKRI.NS","ZOMATO.NS","PAYTM.NS","POLICYBZR.NS",
    "DELHIVERY.NS","NYKAA.NS","CARTRADE.NS","EASEMYTRIP.NS","IRCTC.NS",
    "RAILTEL.NS","RVNL.NS","IRFC.NS","HUDCO.NS","RECLTD.NS",
    "PFC.NS","SJVN.NS","NHPC.NS","TATAPOWER.NS","ADANIGREEN.NS",
    "ADANITRANS.NS","TORNTPOWER.NS","CESC.NS","JSW.NS","SAIL.NS",
    "HINDALCO.NS","VEDL.NS","NMDC.NS","MOIL.NS","NATIONALUM.NS"
]

# International Stocks (major global companies on yfinance)
INTERNATIONAL_TICKERS = [
    "ASML","TSM","BABA","NVO","SAP","TM","SHOP","SONY","HSBC","RY",
    "TD","BP","SHEL","UL","DEO","BTI","NVS","RHHBY","AZN","GSK",
    "SNY","SAN","BBVA","ING","PHG","SIEGY","BAYZF","VLKAF","BMWYY","MBGYY",
    "BHP","RIO","VALE","AMX","ITUB","BBD","PBR","CIB","BAP","GGAL",
    "MELI","SE","GRAB","BIDU","JD","PDD","NTES","BILI","TME","IQ",
    "KB","SHG","SKM","KEP","HDB","WIT","IBN","VEDL","ENIC","ERJ",
    "ABEV","XP","GGB","SID","TIMB","BSBR","BRFS","EMBR","PAGS","STNE",
    "TCOM","ZTO","YMM","VNET","CAN","FINV","QFIN","LIAN","BZ","NIU"
]

# Growth Stocks
GROWTH_TICKERS = [
    "PLTR","SNOW","CRWD","DDOG","ZS","OKTA","MDB","CFLT","GTLB",
    "PATH","AI","SOUN","RBRK","RDDT","HOOD","COIN","SQ","PYPL",
    "AFRM","UPST","SOFI","NU","MRVL","ON","MPWR","ENPH","FSLR",
    "SEDG","RUN","NET","MNDY","BILL","HUBS","TWLO","ZI","DOCN",
    "ESTC","ELASTIC","APPN","PROG","IONQ","QUBT","RGTI","ARQQ",
    "ASTS","RKLB","LUNR","MNTS","ASTR","SPCE","RDW","VORB"
]

# S&P 400 MidCap — most traded mid-cap US stocks
MIDCAP_TICKERS = [
    "AXON","TRGP","GDDY","EQT","CBOE","NDAQ","NTAP","ZBRA","WST","POOL",
    "TYL","PAYC","MANH","ALLE","BWXT","SNX","HII","LECO","RNR","SAIA",
    "INGR","LSTR","PCVX","CWST","FDS","TREX","MEDP","ITCI","MMSI","CASY",
    "LNTH","SFBS","BGNE","ROIV","IRTC","ACHC","PRCT","ITGR","ICUI","AGIO",
    "MATX","EPAM","GLDD","GKOS","KRYS","ACAD","EXAS","NTRA","TDOC","HIMS",
    "CELH","PTON","DKNG","PENN","RSI","AGS","GENI","SGHC","CARG","OPEN",
    "OPENDOOR","Z","ZG","RDFN","EXPI","COMP","HHC","FPH","AIRC","NXST",
    "SIRI","IHRT","GTN","SBGI","AMC","CNK","IMAX","LYV","SEM","ACHC",
    "ENVA","CURO","PRAA","NAVI","SLM","NMIH","RDN","ESNT","MGIC","MTG",
    "ESGR","ARGO","ACGL","RYAN","GSHD","KNSL","KINSALE","KINS","NGHC","HCI",
    "JOBY","ACHR","LILM","EVTL","BLDE","SKYH","ATRO","KTOS","RCAT","AVAV",
    "CEVA","FORM","POWI","DIOD","OSIS","TTMI","VIAV","COHU","ONTO","UCTT",
    "AEIS","ICHR","AMAT","LAM","KLAC","MKSI","ENTG","AZTA","ACMR","NVMI",
    "WOLF","CREE","AEVA","OUST","LIDR","INVZ","MVIS","LAZR","VLDR","AEYE",
    "BLNK","CHPT","EVGO","NXTP","FREYR","MVST","NKLA","WKHS","RIDE","GOEV",
    "FSR","LCID","RIVN","FFIE","MULN","SOLO","XPEV","LI","NIO","ZEEKR"
]

# NSE India — extended liquid stocks
INDIAN_EXTENDED_TICKERS = [
    "BAJAJ-AUTO.NS","HEROMOTOCO.NS","EICHERMOT.NS","TVSMOTORS.NS","M&M.NS",
    "ASHOKLEY.NS","TVSMOTOR.NS","ESCORTS.NS","FORCEMOT.NS","TIINDIA.NS",
    "BOSCHLTD.NS","MOTHERSON.NS","BHARATFORG.NS","APOLLOTYRE.NS","CEATLTD.NS",
    "MRF.NS","BALKRISIND.NS","EXIDEIND.NS","AMARAJABAT.NS","SUNDRMFAST.NS",
    "DIVISLAB.NS","AUROPHARMA.NS","ALKEM.NS","TORNTPHARM.NS","IPCALAB.NS",
    "GLENMARK.NS","NATCOPHAR.NS","AJANTPHARMA.NS","GRANULES.NS","LAURUSLABS.NS",
    "PGHH.NS","COLPAL.NS","EMAMILTD.NS","BAJAJCON.NS","JYOTHYLAB.NS",
    "TATAELXSI.NS","LTTS.NS","MPHASIS.NS","COFORGE.NS","PERSISTENT.NS",
    "ROUTE.NS","TANLA.NS","MASTEK.NS","KPITTECH.NS","SONATSOFTW.NS",
    "BANKBARODA.NS","PNB.NS","CANBK.NS","UNIONBANK.NS","INDIANB.NS",
    "IOB.NS","UCOBANK.NS","CENTRALBK.NS","MAHABANK.NS","PSB.NS",
    "MUTHOOTFIN.NS","MANAPPURAM.NS","CHOLAFIN.NS","SUNDARMFIN.NS","M&MFIN.NS",
    "SHRIRAMFIN.NS","LIChousing.NS","CANFINHOME.NS","GRUH.NS","REPCO.NS",
    "HDFCAMC.NS","NIPPONLIFE.NS","ICICIPRU.NS","ABSLAMC.NS","UTIAMC.NS",
    "NAUKRI.NS","JUSTDIAL.NS","MATRIMONY.NS","MAKEMYTRIP.NS","YATRA.NS",
    "TATACOMM.NS","HFCL.NS","STLTECH.NS","TEJASNET.NS","GTLINFRA.NS",
    "TATAPOWER.NS","CESC.NS","TORNTPOWER.NS","JSWENERGY.NS","INOXWIND.NS",
    "SUZLON.NS","RPOWER.NS","ADANIPOWER.NS","JPPOWER.NS","NHPC.NS",
    "NATIONALUM.NS","HINDZINC.NS","HINDCOPPER.NS","MOIL.NS","GMRINFRA.NS",
    "IRB.NS","SADBHAV.NS","KNRCON.NS","PNC.NS","HGINFRA.NS",
    "PHOENIXLTD.NS","DLF.NS","GODREJPROP.NS","OBEROIRLTY.NS","PRESTIGE.NS"
]

ALL_TRADITIONAL_TICKERS = SP500_TICKERS + ETF_TICKERS + REIT_TICKERS + COMMODITY_TICKERS + BOND_TICKERS + INDIAN_TICKERS + INTERNATIONAL_TICKERS + GROWTH_TICKERS + MIDCAP_TICKERS + INDIAN_EXTENDED_TICKERS
