# S&P 500 — all 503 components
SP500_TICKERS = [
    "AAPL","MSFT","NVDA","GOOGL","GOOG","AMZN","META","TSLA","BRK-B","BRK-A",
    "UNH","LLY","JPM","V","XOM","MA","AVGO","PG","HD","COST","MRK","CVX","ABBV",
    "CRM","ACN","MCD","WMT","BAC","NFLX","AMD","PEP","KO","TMO","CSCO","LIN",
    "DHR","ABT","TXN","PM","CMCSA","ORCL","WFC","NEE","RTX","T","BMY","QCOM",
    "INTU","AMGN","UNP","MS","GE","IBM","HON","GS","CAT","SPGI","ISRG","LOW",
    "ELV","BKNG","VRTX","DE","MDLZ","ADI","GILD","BLK","AXP","SYK","REGN","MMC",
    "PLD","SBUX","PANW","CB","CI","ETN","ZTS","BSX","LRCX","KLAC","SO","DUK",
    "NOC","HUM","AON","MO","ITW","TGT","SHW","GD","MCO","CME","EQIX","ICE",
    "EMR","FCX","PH","NSC","CL","FDX","TDG","USB","ROP","APD","CTAS","MSI",
    "ECL","ADSK","ANET","OXY","PCAR","ORLY","AZO","NXPI","MCHP","WDAY","IDXX",
    "MET","PSA","AFL","STZ","EW","SLB","ALL","PGR","TT","A","NKE","CHTR",
    "WELL","MAR","GWW","HLT","CARR","FTNT","AIG","DHI","NEM","PAYX","ODFL",
    "FAST","KMB","CTVA","EFX","MTD","VRSK","MNST","HES","F","GM","LHX","HIG",
    "TEL","SRE","KEYS","OTIS","ROK","AME","BDX","WM","APH","GEHC","FANG",
    "CPRT","GPN","AWK","KHC","CBRE","PCG","EXC","XEL","ED","D","FE","ETR",
    "ACGL","BALL","DTE","CMS","PPL","LNT","AEE","WEC","ES","CNP","NI","PNW",
    "IEX","DOV","CINF","TFC","RF","CFG","FITB","HBAN","NTRS","STT","MTB",
    "KEY","ZION","CMA","SNA","PNR","IR","EXPD","JBHT","UAL","DAL","LUV","AAL",
    "CCL","RCL","NCLH","MGM","LVS","WYNN","CZR","MHK","PHM","LEN","NVR","TOL",
    "BXP","VNO","SLG","CPT","EQR","AVB","UDR","MAA","NNN","O","STOR","WPC",
    "MPW","HR","OHI","PEAK","VTR","SBAC","AMT","CCI","DLR","EQIX","QTS",
    "ARE","BRX","KIM","REG","FRT","SPG","MAC","CBL","TCO","WRI","DDR","AKR",
    "ADC","EPRT","NTST","RCPI","VICI","GLPI","GLP","STAG","TRNO","EXR","LSI",
    "CUZ","PDM","DEI","HPP","CLI","PGRE","ESRT","VRE","NXRT","IIPR","COLD",
    "REXR","CUBE","NSA","JBGS","KRC","BDN","OFC","PKST","FSP","RLJ","RHP",
    "HST","DRH","PEB","SHO","CLDT","APLE","BRAEMAR","INN","CHSP","SVC",
    "NWFL","VHI","ALX","ESBA","JRJR","GOOD","LAND","PSTL","SACH","GPMT",
    "NOW","SNOW","PLTR","NET","DDOG","CRWD","ZS","OKTA","MDB","CFLT","GTLB",
    "UiPath","PATH","AI","C3AI","BBAI","SOUN","RBRK","RDDT","HOOD","COIN",
    "SQ","PYPL","AFRM","UPST","LC","SOFI","NU","DFS","COF","ADS","SYF",
    "ALLY","SC","CACC","ECPG","OMF","WRLD","QRVO","SWKS","XLNX","MRVL",
    "ON","MPWR","ALGM","SITM","WOLF","SLAB","SMTC","CRUS","MTSI","ENPH",
    "FSLR","SEDG","NOVA","ARRY","RUN","SPWR","CSIQ","JKS","DQ","MAXN","SHLS"
]

# Crypto — yfinance format (200 pairs)
CRYPTO_TICKERS = [
    "BTC-USD","ETH-USD","BNB-USD","XRP-USD","SOL-USD","ADA-USD","DOGE-USD",
    "TRX-USD","DOT-USD","MATIC-USD","LTC-USD","SHIB-USD","AVAX-USD","LINK-USD",
    "ATOM-USD","XLM-USD","BCH-USD","XMR-USD","ETC-USD","ALGO-USD","VET-USD",
    "FIL-USD","ICP-USD","APT-USD","ARB-USD","OP-USD","NEAR-USD","HBAR-USD",
    "QNT-USD","GRT-USD","AAVE-USD","MKR-USD","SNX-USD","CRV-USD","UNI-USD",
    "SUSHI-USD","COMP-USD","YFI-USD","1INCH-USD","BAL-USD","ZRX-USD","KNC-USD",
    "MANA-USD","SAND-USD","AXS-USD","GALA-USD","ENJ-USD","CHZ-USD","FLOW-USD",
    "IMX-USD","RNDR-USD","LRC-USD","SKL-USD","CELR-USD","COTI-USD","CTSI-USD",
    "OCEAN-USD","FET-USD","AGIX-USD","NMR-USD","GNO-USD","REP-USD","MLN-USD",
    "REN-USD","BNT-USD","ANKR-USD","CVC-USD","DNT-USD","FUN-USD","MANA-USD",
    "OMG-USD","PAX-USD","POWR-USD","RLC-USD","STORJ-USD","ZEN-USD","ZEC-USD",
    "DASH-USD","DCR-USD","WAVES-USD","QTUM-USD","ONT-USD","ZIL-USD","ICX-USD",
    "IOST-USD","WAN-USD","LSK-USD","NANO-USD","SC-USD","STEEM-USD","DGB-USD",
    "SYS-USD","VIA-USD","XVG-USD","MAID-USD","GAME-USD","XEM-USD","STRAT-USD",
    "KMD-USD","ARDR-USD","NXT-USD","BURST-USD","PPC-USD","NVC-USD","FTC-USD",
    "BTG-USD","ZCL-USD","XZC-USD","PIVX-USD","BLOCK-USD","CLAM-USD","VTC-USD",
    "BLK-USD","UBQ-USD","MONA-USD","RDD-USD","DOGE-USD","VRC-USD","NOTE-USD",
    "MEC-USD","KORE-USD","MINT-USD","AEON-USD","CGB-USD","TRC-USD","SLR-USD",
    "CAP-USD","MAX-USD","NMC-USD","IXC-USD","FLO-USD","XPM-USD","EAC-USD",
    "MZC-USD","NET-USD","TAG-USD","MRC-USD","HBN-USD","APEX-USD","APC-USD",
    "NLG-USD","BTA-USD","GLC-USD","PXI-USD","SXC-USD","ZEIT-USD","BELA-USD",
    "XBC-USD","BIC-USD","DTC-USD","ELP-USD","SUPER-USD","CON-USD","KARMA-USD",
    "CLUB-USD","XCASH-USD","PND-USD","CLOAK-USD","PKB-USD","NYAN-USD","2GIVE-USD",
    "GRS-USD","AUR-USD","AC-USD","IOC-USD","MED-USD","MNE-USD","PROC-USD",
    "CACH-USD","PTC-USD","OSC-USD","KTK-USD","GPS-USD","HODL-USD","XSPEC-USD",
    "SMC-USD","BLC-USD","SOON-USD","XMCC-USD","PHR-USD","XCO-USD","SHND-USD",
    "ARG-USD","MRS-USD","XCN-USD","TOR-USD","BOST-USD","DANK-USD","USNBT-USD",
    "FRN-USD","EDRC-USD","SRC-USD","FLT-USD","EMC2-USD","CANN-USD","GXC-USD",
    "CHIP-USD","SPRTS-USD","XPY-USD","BTB-USD","ADZ-USD","BENJI-USD","TOPAZ-USD"
]

# ETFs (100)
ETF_TICKERS = [
    "SPY","QQQ","VTI","VOO","IWM","DIA","VEA","VWO","EFA","EEM",
    "IEMG","SCHB","ITOT","SPDW","VT","VXUS","GLD","SLV","IAU","GLDM",
    "XLK","XLF","XLE","XLV","XLI","XLB","XLU","XLP","XLRE","XLC",
    "ARKK","ARKG","ARKW","ARKF","ARKQ","IBB","VGT","SOXX","HACK","BOTZ",
    "FINX","BLOK","LIT","ICLN","ACES","TAN","FAN","GRID","PBW","QCLN",
    "TLT","IEF","HYG","LQD","BND","SHY","VGIT","VCIT","VCLT","AGG",
    "MUB","TIP","STIP","VTIP","BNDX","USHY","ANGL","EMHY","FALN","SPSB",
    "VNQ","SCHH","REZ","VNQI","REM","MORT","SRET","KBWY","FFR","HOMZ",
    "GDX","GDXJ","SIL","SILJ","PPLT","PALL","CPER","WOOD","MOO","WEAT",
    "CORN","SOYB","JJG","NIB","CANE","JO","BAL","UNG","USO","BNO"
]

# REITs (50) — individual companies not ETFs
REIT_TICKERS = [
    "AMT","PLD","EQIX","SPG","PSA","DLR","CCI","O","WELL","AVB",
    "EQR","VTR","BXP","ARE","MAA","UDR","NNN","CPT","EXR","SBAC",
    "KIM","REG","FRT","VICI","GLPI","STAG","TRNO","COLD","REXR","CUBE",
    "NSA","IRM","QTS","SLG","VNO","HPP","DEI","KRC","OFC","CLI",
    "RHP","HST","DRH","PEB","APLE","MPW","OHI","PEAK","HR","JBGS"
]

# Commodities (via ETF/futures proxies on yfinance)
COMMODITY_TICKERS = [
    "GC=F","SI=F","CL=F","BZ=F","NG=F","HG=F","PL=F","PA=F",
    "ZW=F","ZC=F","ZS=F","KC=F","CT=F","CC=F","SB=F","OJ=F",
    "LE=F","GF=F","HE=F","LBS=F","RB=F","HO=F","BO=F","ZO=F",
    "ZR=F","ZM=F","GDK=F","DC=F","ZL=F","ZT=F"
]

# Bonds (via ETF proxies on yfinance)
BOND_TICKERS = [
    "TLT","IEF","SHY","BND","AGG","LQD","HYG","JNK",
    "TIP","VTIP","BNDX","EMB","MUB","SHV","GOVT",
    "VGSH","VGIT","VGLT","BSV","BIV","BLV","VCSH","VCIT","VCLT",
    "SCHZ","SCHR","SCHI","SCHQ","STIP","LTPZ"
]

# Indian Stocks (NSE via yfinance .NS suffix)
INDIAN_TICKERS = [
    "RELIANCE.NS","TCS.NS","HDFCBANK.NS","INFY.NS","ICICIBANK.NS",
    "HINDUNILVR.NS","SBIN.NS","BHARTIARTL.NS","ITC.NS","KOTAKBANK.NS",
    "LT.NS","AXISBANK.NS","ASIANPAINT.NS","MARUTI.NS","SUNPHARMA.NS",
    "TITAN.NS","ULTRACEMCO.NS","WIPRO.NS","HCLTECH.NS","BAJFINANCE.NS",
    "NESTLEIND.NS","POWERGRID.NS","NTPC.NS","ONGC.NS","JSWSTEEL.NS",
    "TATAMOTORS.NS","TECHM.NS","ADANIENT.NS","ADANIPORTS.NS","COALINDIA.NS",
    "BAJAJFINSV.NS","HDFCLIFE.NS","SBILIFE.NS","DIVISLAB.NS","DRREDDY.NS",
    "CIPLA.NS","APOLLOHOSP.NS","BRITANNIA.NS","DABUR.NS","MARICO.NS",
    "PIDILITIND.NS","BERGEPAINT.NS","HAVELLS.NS","VOLTAS.NS","WHIRLPOOL.NS",
    "TATACONSUM.NS","UBL.NS","MCDOWELL-N.NS","RADICO.NS","TATACOMM.NS",
    "INDIAMART.NS","NAUKRI.NS","ZOMATO.NS","PAYTM.NS","POLICYBZR.NS",
    "DELHIVERY.NS","NYKAA.NS","CARTRADE.NS","EASEMYTRIP.NS","IRCTC.NS",
    "RAILTEL.NS","RVNL.NS","IRFC.NS","HUDCO.NS","RECLTD.NS",
    "PFC.NS","SJVN.NS","NHPC.NS","TATAPOWER.NS","ADANIGREEN.NS",
    "ADANITRANS.NS","TORNTPOWER.NS","CESC.NS","JSW.NS","SAIL.NS",
    "HINDALCO.NS","VEDL.NS","NMDC.NS","MOIL.NS","NATIONALUM.NS"
]

# International Stocks (major global companies on yfinance)
INTERNATIONAL_TICKERS = [
    "ASML","TSM","BABA","NVO","SAP","TM","SHOP","SONY","HSBC","RY",
    "TD","BP","SHEL","UL","DEO","BTI","NVS","RHHBY","AZN","GSK",
    "SNY","SAN","BBVA","ING","PHG","SIEGY","BAYZF","VLKAF","BMWYY","MBGYY",
    "BHP","RIO","VALE","AMX","ITUB","BBD","PBR","CIB","BAP","GGAL",
    "MELI","SE","GRAB","BIDU","JD","PDD","NTES","BILI","TME","IQ",
    "KB","SHG","SKM","KEP","HDB","WIT","IBN","VEDL","ENIC","ERJ",
    "ABEV","XP","GGB","SID","TIMB","BSBR","BRFS","EMBR","PAGS","STNE",
    "TCOM","ZTO","YMM","VNET","CAN","FINV","QFIN","LIAN","BZ","NIU"
]

# Growth Stocks
GROWTH_TICKERS = [
    "PLTR","SNOW","CRWD","DDOG","ZS","OKTA","MDB","CFLT","GTLB",
    "PATH","AI","SOUN","RBRK","RDDT","HOOD","COIN","SQ","PYPL",
    "AFRM","UPST","SOFI","NU","MRVL","ON","MPWR","ENPH","FSLR",
    "SEDG","RUN","NET","MNDY","BILL","HUBS","TWLO","ZI","DOCN",
    "ESTC","ELASTIC","APPN","PROG","IONQ","QUBT","RGTI","ARQQ",
    "ASTS","RKLB","LUNR","MNTS","ASTR","SPCE","RDW","VORB"
]

# S&P 400 MidCap — most traded mid-cap US stocks
MIDCAP_TICKERS = [
    "AXON","TRGP","GDDY","EQT","CBOE","NDAQ","NTAP","ZBRA","WST","POOL",
    "TYL","PAYC","MANH","ALLE","BWXT","SNX","HII","LECO","RNR","SAIA",
    "INGR","LSTR","PCVX","CWST","FDS","TREX","MEDP","ITCI","MMSI","CASY",
    "LNTH","SFBS","BGNE","ROIV","IRTC","ACHC","PRCT","ITGR","ICUI","AGIO",
    "MATX","EPAM","GLDD","GKOS","KRYS","ACAD","EXAS","NTRA","TDOC","HIMS",
    "CELH","PTON","DKNG","PENN","RSI","AGS","GENI","SGHC","CARG","OPEN",
    "OPENDOOR","Z","ZG","RDFN","EXPI","COMP","HHC","FPH","AIRC","NXST",
    "SIRI","IHRT","GTN","SBGI","AMC","CNK","IMAX","LYV","SEM","ACHC",
    "ENVA","CURO","PRAA","NAVI","SLM","NMIH","RDN","ESNT","MGIC","MTG",
    "ESGR","ARGO","ACGL","RYAN","GSHD","KNSL","KINSALE","KINS","NGHC","HCI",
    "JOBY","ACHR","LILM","EVTL","BLDE","SKYH","ATRO","KTOS","RCAT","AVAV",
    "CEVA","FORM","POWI","DIOD","OSIS","TTMI","VIAV","COHU","ONTO","UCTT",
    "AEIS","ICHR","AMAT","LAM","KLAC","MKSI","ENTG","AZTA","ACMR","NVMI",
    "WOLF","CREE","AEVA","OUST","LIDR","INVZ","MVIS","LAZR","VLDR","AEYE",
    "BLNK","CHPT","EVGO","NXTP","FREYR","MVST","NKLA","WKHS","RIDE","GOEV",
    "FSR","LCID","RIVN","FFIE","MULN","SOLO","XPEV","LI","NIO","ZEEKR"
]

# NSE India — extended liquid stocks
INDIAN_EXTENDED_TICKERS = [
    "BAJAJ-AUTO.NS","HEROMOTOCO.NS","EICHERMOT.NS","TVSMOTORS.NS","M&M.NS",
    "ASHOKLEY.NS","TVSMOTOR.NS","ESCORTS.NS","FORCEMOT.NS","TIINDIA.NS",
    "BOSCHLTD.NS","MOTHERSON.NS","BHARATFORG.NS","APOLLOTYRE.NS","CEATLTD.NS",
    "MRF.NS","BALKRISIND.NS","EXIDEIND.NS","AMARAJABAT.NS","SUNDRMFAST.NS",
    "DIVISLAB.NS","AUROPHARMA.NS","ALKEM.NS","TORNTPHARM.NS","IPCALAB.NS",
    "GLENMARK.NS","NATCOPHAR.NS","AJANTPHARMA.NS","GRANULES.NS","LAURUSLABS.NS",
    "PGHH.NS","COLPAL.NS","EMAMILTD.NS","BAJAJCON.NS","JYOTHYLAB.NS",
    "TATAELXSI.NS","LTTS.NS","MPHASIS.NS","COFORGE.NS","PERSISTENT.NS",
    "ROUTE.NS","TANLA.NS","MASTEK.NS","KPITTECH.NS","SONATSOFTW.NS",
    "BANKBARODA.NS","PNB.NS","CANBK.NS","UNIONBANK.NS","INDIANB.NS",
    "IOB.NS","UCOBANK.NS","CENTRALBK.NS","MAHABANK.NS","PSB.NS",
    "MUTHOOTFIN.NS","MANAPPURAM.NS","CHOLAFIN.NS","SUNDARMFIN.NS","M&MFIN.NS",
    "SHRIRAMFIN.NS","LIChousing.NS","CANFINHOME.NS","GRUH.NS","REPCO.NS",
    "HDFCAMC.NS","NIPPONLIFE.NS","ICICIPRU.NS","ABSLAMC.NS","UTIAMC.NS",
    "NAUKRI.NS","JUSTDIAL.NS","MATRIMONY.NS","MAKEMYTRIP.NS","YATRA.NS",
    "TATACOMM.NS","HFCL.NS","STLTECH.NS","TEJASNET.NS","GTLINFRA.NS",
    "TATAPOWER.NS","CESC.NS","TORNTPOWER.NS","JSWENERGY.NS","INOXWIND.NS",
    "SUZLON.NS","RPOWER.NS","ADANIPOWER.NS","JPPOWER.NS","NHPC.NS",
    "NATIONALUM.NS","HINDZINC.NS","HINDCOPPER.NS","MOIL.NS","GMRINFRA.NS",
    "IRB.NS","SADBHAV.NS","KNRCON.NS","PNC.NS","HGINFRA.NS",
    "PHOENIXLTD.NS","DLF.NS","GODREJPROP.NS","OBEROIRLTY.NS","PRESTIGE.NS"
]

ALL_TRADITIONAL_TICKERS = SP500_TICKERS + ETF_TICKERS + REIT_TICKERS + COMMODITY_TICKERS + BOND_TICKERS + INDIAN_TICKERS + INTERNATIONAL_TICKERS + GROWTH_TICKERS + MIDCAP_TICKERS + INDIAN_EXTENDED_TICKERS

# Russell 1000 additional stocks not in SP500
RUSSELL_TICKERS = [
    "AXON","GDDY","TRGP","EQT","CBOE","NTAP","WST","POOL","TYL","PAYC",
    "MANH","ALLE","SNX","HII","LECO","RNR","SAIA","INGR","LSTR","FDS",
    "TREX","MEDP","CASY","MATX","EPAM","GKOS","KRYS","ACAD","EXAS","NTRA",
    "CELH","DKNG","PENN","CARG","Z","ZG","RDFN","NXST","LYV","JOBY",
    "ACHR","AVAV","CEVA","FORM","POWI","DIOD","TTMI","VIAV","COHU","ONTO",
    "UCTT","AEIS","ICHR","MKSI","ENTG","AZTA","ACMR","NVMI","WOLF","AEVA",
    "BLNK","CHPT","EVGO","IONQ","QUBT","RGTI","ASTS","RKLB","LUNR","SPCE",
    "RELY","DUOL","CWAN","GTLB","BRZE","PCVX","ROIV","IRTC","ACHC","PRCT",
    "ITGR","ICUI","AGIO","GLDD","MNDY","BILL","HUBS","TWLO","ZI","DOCN",
    "ESTC","APPN","ABNB","DASH","RBLX","U","BMBL","MTCH","IAC","ANGI",
    "WBD","PARA","FOXA","FOX","NWSA","NWS","LUMN","FYBR","CABO","WOW",
    "LBRDA","LBRDK","CHTR","ATUS","CNSL","SHEN","OOMA","LMNR","TIGO","LILAK",
    "VNET","CAN","FINV","QFIN","LIAN","NIU","XPEV","LI","NIO","ZEEKR",
    "MNSO","KANZHUN","BOSS","LAIX","GOTU","IQ","MOMO","YY","JOYY","DOYU"
]

# European & Asian large caps (via US ADRs)
ADR_TICKERS = [
    "ASML","TSM","BABA","NVO","SAP","TM","SONY","HSBC","RY","TD",
    "BP","SHEL","UL","DEO","BTI","NVS","RHHBY","AZN","GSK","SNY",
    "SAN","BBVA","ING","PHG","SIEGY","BAYZF","BMWYY","MBGYY","BHP","RIO",
    "VALE","AMX","ITUB","BBD","PBR","CIB","BAP","GGAL","MELI","SE",
    "GRAB","BIDU","JD","PDD","NTES","BILI","TME","KB","SHG","SKM",
    "KEP","HDB","WIT","IBN","ENIC","ERJ","ABEV","XP","GGB","SID",
    "TIMB","BSBR","BRFS","EMBR","PAGS","STNE","TCOM","ZTO","YMM","BZ",
    "RELX","WPP","EXPN","DGE","ULVR","AHT","BARC","LLOY","VOD","BT",
    "SMFG","MFG","MTU","NMR","MUFG","HMC","FUJIY","TOYOF","NSANY","CRRFY",
    "ANZBY","NABZY","WBKLY","MQBKY","CGAOF","CBAUY","CMWAY","AIRYY","QANTAS","FMG"
]

# More NSE India stocks
INDIAN_LARGE_TICKERS = [
    "BAJAJHLDNG.NS","PIDILITIND.NS","BERGEPAINT.NS","HAVELLS.NS","VOLTAS.NS",
    "TATACONSUM.NS","UBL.NS","RADICO.NS","TATACOMM.NS","INDIAMART.NS",
    "ZOMATO.NS","DELHIVERY.NS","NYKAA.NS","IRCTC.NS","RAILTEL.NS",
    "RVNL.NS","IRFC.NS","HUDCO.NS","RECLTD.NS","PFC.NS",
    "SJVN.NS","NHPC.NS","ADANIGREEN.NS","ADANITRANS.NS","TORNTPOWER.NS",
    "JSWSTEEL.NS","HINDALCO.NS","VEDL.NS","NMDC.NS","NATIONALUM.NS",
    "AUROPHARMA.NS","ALKEM.NS","TORNTPHARM.NS","IPCALAB.NS","GLENMARK.NS",
    "NATCOPHAR.NS","AJANTPHARMA.NS","GRANULES.NS","LAURUSLABS.NS","PGHH.NS",
    "COLPAL.NS","EMAMILTD.NS","BAJAJCON.NS","JYOTHYLAB.NS","TATAELXSI.NS",
    "LTTS.NS","MPHASIS.NS","COFORGE.NS","PERSISTENT.NS","ROUTE.NS",
    "TANLA.NS","MASTEK.NS","KPITTECH.NS","BANKBARODA.NS","PNB.NS",
    "CANBK.NS","UNIONBANK.NS","INDIANB.NS","MUTHOOTFIN.NS","MANAPPURAM.NS",
    "CHOLAFIN.NS","SUNDARMFIN.NS","SHRIRAMFIN.NS","HDFCAMC.NS","NIPPONLIFE.NS",
    "ICICIPRU.NS","ABSLAMC.NS","UTIAMC.NS","JUSTDIAL.NS","MATRIMONY.NS",
    "TATAPOWER.NS","CESC.NS","JSWENERGY.NS","INOXWIND.NS","SUZLON.NS",
    "DLF.NS","GODREJPROP.NS","OBEROIRLTY.NS","PRESTIGE.NS","PHOENIXLTD.NS",
    "BAJAJ-AUTO.NS","HEROMOTOCO.NS","EICHERMOT.NS","TVSMOTORS.NS","ASHOKLEY.NS",
    "BOSCHLTD.NS","MOTHERSON.NS","BHARATFORG.NS","APOLLOTYRE.NS","MRF.NS",
    "DIVISLAB.NS","APOLLOHOSP.NS","FORTIS.NS","MAXHEALTH.NS","NARAYANHA.NS",
    "LALPATHLAB.NS","METROPOLIS.NS","THYROCARE.NS","KRSNAA.NS","VIJAYA.NS"
]

# Thematic ETFs and sector funds
THEMATIC_ETF_TICKERS = [
    "ARKK","ARKG","ARKW","ARKF","ARKQ","ARKX","PRNT","IZRL",
    "BOTZ","ROBO","IRBO","THNQ","WTAI","AIQ","AIEQ",
    "ICLN","QCLN","TAN","FAN","ACES","CNRG","SMOG","EFAX",
    "HACK","CIBR","BUG","IHAK","WCBR","ETHO",
    "LIT","BATT","DRIV","IDRV","KARS","MOTO","CARZ",
    "FINX","IPAY","KOIN","BLOK","BKCH","LEGR","DAPP",
    "SOXX","SMH","PSI","XSD","FTXL","SOXQ",
    "IBB","XBI","ARKG","GNOM","IDNA","IBBQ","SBIO",
    "GDX","GDXJ","SIL","SILJ","PPLT","PALL","CPER","REMX",
    "MOO","VEGI","PAGG","COW","JO","NIB","BAL","SOYB","WEAT","CORN",
    "JETS","PPA","ITA","XAR","DFEN","UFO","ROKT",
    "ITB","XHB","HOMZ","REZ","MORT","REM","SRET"
]

# US Small/Micro Cap growth
SMALLCAP_TICKERS = [
    "IONQ","QUBT","RGTI","ARQQ","ASTS","RKLB","LUNR","MNTS","ASTR",
    "JOBY","ACHR","LILM","EVTL","BLDE","SKYH","ATRO","KTOS","RCAT",
    "CEVA","FORM","DIOD","OSIS","TTMI","VIAV","COHU","ONTO","UCTT",
    "AEIS","ICHR","MKSI","ENTG","AZTA","ACMR","NVMI","AEVA","OUST",
    "BLNK","CHPT","EVGO","NXTP","FREYR","MVST","WKHS","GOEV","FSR",
    "XPEV","LI","NIO","ZEEKR","MNSO","LAIX","GOTU","DOYU","HUYA",
    "GPRO","HEAR","IMAX","CNK","AMC","NCMI","MANU","MSGS","SPHR",
    "PTON","XPOF","BFCO","GXII","LULU","SKX","CROX","DECK","ONON",
    "YETI","BIRD","HASBRO","MAT","JAKK","FNKO","LEJU","PRDO","LOPE",
    "STRA","LAUR","ARCO","PZZA","FAT","JACK","DENN","EAT","DIN","CAKE"
]

# London Stock Exchange (.L suffix)
LSE_TICKERS = [
    "SHEL.L","AZN.L","HSBA.L","ULVR.L","RIO.L","BP.L","GSK.L","REL.L",
    "NG.L","LSEG.L","CPG.L","PRU.L","BATS.L","FLTR.L","CRH.L","RKT.L",
    "EXPN.L","WPP.L","SGRO.L","LAND.L","BLND.L","HMSO.L","INTU.L","BME.L",
    "BA.L","RR.L","MGGT.L","QQ.L","AUTO.L","MNDI.L","SMDS.L","WTB.L",
    "ABF.L","OCDO.L","MKS.L","NEXT.L","JD.L","SPX.L","DGE.L","BDEV.L",
    "BWY.L","PSN.L","TW.L","MTO.L","IMB.L","TSCO.L","SBRY.L","MRW.L",
    "III.L","SVT.L","SSE.L","UU.L","PNN.L","CNA.L","BRBY.L","FERG.L",
    "SDR.L","HLMA.L","WEIR.L","IMI.L","SMIN.L","RMSV.L","MEG.L","SN.L",
]

# Toronto Stock Exchange (.TO suffix)
TSX_TICKERS = [
    "RY.TO","TD.TO","BNS.TO","BMO.TO","CM.TO","MFC.TO","SLF.TO","GWO.TO",
    "POW.TO","IAG.TO","ENB.TO","TRP.TO","CNQ.TO","SU.TO","CVE.TO","IMO.TO",
    "CP.TO","CNR.TO","WCN.TO","ATD.TO","MG.TO","ABX.TO","AEM.TO","K.TO",
    "AGI.TO","KL.TO","WPM.TO","FNV.TO","PAAS.TO","FR.TO","ERO.TO","LUN.TO",
    "FM.TO","CS.TO","HBM.TO","TCK-B.TO","TECK-B.TO","NTR.TO","AGU.TO",
    "CCO.TO","URE.TO","BHC.TO","ACO-X.TO","SJ.TO","IFC.TO","EMP-A.TO",
    "L.TO","MRU.TO","SAP.TO","DOL.TO","GIB-A.TO","CSU.TO","OTEX.TO","BB.TO",
    "SHOP.TO","LSPD.TO","NVEI.TO","REAL.TO","DSG.TO","TOI.TO","DCM.TO",
]

# Australian Stock Exchange (.AX suffix)
ASX_TICKERS = [
    "BHP.AX","CBA.AX","CSL.AX","NAB.AX","WBC.AX","ANZ.AX","MQG.AX","WES.AX",
    "WOW.AX","RIO.AX","FMG.AX","TLS.AX","GMG.AX","REA.AX","COL.AX","ALL.AX",
    "TCL.AX","QAN.AX","AGL.AX","ORG.AX","STO.AX","WDS.AX","IEL.AX","CAR.AX",
    "SEK.AX","XRO.AX","CPU.AX","SHL.AX","RHC.AX","RMD.AX","COH.AX","PME.AX",
    "ALX.AX","ASX.AX","SUN.AX","QBE.AX","IAG.AX","MPL.AX","NHF.AX","HLS.AX",
    "MIN.AX","AWC.AX","S32.AX","NST.AX","EVN.AX","NCM.AX","OZL.AX","IGO.AX",
    "LYC.AX","ILU.AX","WHC.AX","NEC.AX","SXL.AX","NWS.AX","NXT.AX","WTC.AX",
]

# Frankfurt Stock Exchange (.DE suffix)
FSE_TICKERS = [
    "SAP.DE","SIE.DE","ALV.DE","MUV2.DE","DTE.DE","BMW.DE","MBG.DE","VOW3.DE",
    "BAS.DE","BAYN.DE","EOAN.DE","RWE.DE","DB1.DE","CBK.DE","DBK.DE","HEI.DE",
    "BEI.DE","ADS.DE","IFX.DE","AIXA.DE","HHFA.DE","SHL.DE","FRE.DE","MTX.DE",
    "SY1.DE","DHER.DE","HEN3.DE","MRK.DE","EVT.DE","ZAL.DE","RKET.DE","DHL.DE",
    "PAH3.DE","HAB.DE","LEO.DE","TUI1.DE","LHA.DE","FME.DE","BOSS.DE","PUM.DE",
]

# Hong Kong Stock Exchange (.HK suffix)
HKEX_TICKERS = [
    "0700.HK","0941.HK","1299.HK","0005.HK","0939.HK","1398.HK","3988.HK",
    "2318.HK","0388.HK","0011.HK","0001.HK","0016.HK","0002.HK","0003.HK",
    "0006.HK","0012.HK","0017.HK","0019.HK","0027.HK","0066.HK","0083.HK",
    "0101.HK","0135.HK","0175.HK","0267.HK","0288.HK","0291.HK","0316.HK",
    "0322.HK","0330.HK","0386.HK","0392.HK","0489.HK","0494.HK","0688.HK",
    "0762.HK","0823.HK","0857.HK","0868.HK","0883.HK","0916.HK","0960.HK",
    "0992.HK","1038.HK","1044.HK","1088.HK","1093.HK","1109.HK","1113.HK",
    "1177.HK","1211.HK","1288.HK","1336.HK","1347.HK","1359.HK","1378.HK",
]

# Tokyo Stock Exchange (.T suffix)
TSE_TICKERS = [
    "7203.T","6758.T","9984.T","8306.T","7974.T","8316.T","6861.T","4063.T",
    "9432.T","8411.T","4543.T","2914.T","8058.T","7267.T","6954.T","9433.T",
    "8031.T","6502.T","4502.T","7751.T","6367.T","8802.T","4661.T","9022.T",
    "8766.T","8001.T","6201.T","7011.T","5108.T","4568.T","9020.T","8035.T",
    "6098.T","4519.T","2801.T","3382.T","8830.T","9613.T","6301.T","7733.T",
]

# Singapore Stock Exchange (.SI suffix)
SGX_TICKERS = [
    "D05.SI","O39.SI","U11.SI","Z74.SI","C6L.SI","BN4.SI","F34.SI","G13.SI",
    "S63.SI","H78.SI","9CI.SI","A17U.SI","ME8U.SI","C38U.SI","N2IU.SI","K71U.SI",
    "AJBU.SI","T82U.SI","RW0U.SI","BUOU.SI","HMN.SI","EB5.SI","5CP.SI","U96.SI",
]

# Paris Stock Exchange (.PA suffix)
EURONEXT_TICKERS = [
    "AI.PA","AIR.PA","ALO.PA","BN.PA","BNP.PA","CA.PA","CAP.PA","CS.PA",
    "DG.PA","DSY.PA","ENGI.PA","ERF.PA","GLE.PA","HO.PA","KER.PA","LHN.PA",
    "LR.PA","MC.PA","ML.PA","MT.PA","OR.PA","ORA.PA","PUB.PA","RI.PA",
    "RMS.PA","RNO.PA","SAF.PA","SAN.PA","SGO.PA","STLA.PA","STM.PA","SU.PA",
    "SW.PA","TE.PA","TFI.PA","TTE.PA","UBI.PA","UG.PA","VIE.PA","VIV.PA",
]

ALL_TRADITIONAL_TICKERS = SP500_TICKERS + ETF_TICKERS + REIT_TICKERS + COMMODITY_TICKERS + BOND_TICKERS + INDIAN_TICKERS + INTERNATIONAL_TICKERS + GROWTH_TICKERS + MIDCAP_TICKERS + INDIAN_EXTENDED_TICKERS + RUSSELL_TICKERS + ADR_TICKERS + INDIAN_LARGE_TICKERS + THEMATIC_ETF_TICKERS + SMALLCAP_TICKERS + LSE_TICKERS + TSX_TICKERS + ASX_TICKERS + FSE_TICKERS + HKEX_TICKERS + TSE_TICKERS + SGX_TICKERS + EURONEXT_TICKERS
